# -*- coding: utf-8 -*-
"""
Created on Sun May 10 02:21:55 2020

@author: Juliano Batistim
"""


# -*- coding: utf-8 -*-
"""ML_20200509_k_means_clustering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q1cxRiOJ6SzsXw6jbt2rOypdzQtYxMsV

# K-Means Clustering

Data: https://drive.google.com/file/d/1HcxYRfJGM95swdJFWKo2WHgJLf2cfHZ5/view?usp=sharing

## Importing the libraries
"""

import matplotlib.pyplot as plt
import pandas as pd

"""## Importing the dataset"""

dataset = pd.read_csv('.\Data\Mall_Customers.csv')
X = dataset.iloc[:, [3, 4]].values

"""## Using the elbow method to find the optimal number of clusters"""

from sklearn.cluster import KMeans
wcss = []
models = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters = i, init = 'k-means++')
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)
    models.append(kmeans)
plt.plot(range(1, 11), wcss)
plt.title('The Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()

"""## Training the K-Means model on the dataset"""

kmeans = models[4]
y_kmeans = kmeans.fit_predict(X)

"""## Visualising the clusters"""

plt.scatter(X[y_kmeans == 0, 0], X[y_kmeans == 0, 1], s = 100, c = 'red', label = 'Cluster 1')
plt.scatter(X[y_kmeans == 1, 0], X[y_kmeans == 1, 1], s = 100, c = 'blue', label = 'Cluster 2')
plt.scatter(X[y_kmeans == 2, 0], X[y_kmeans == 2, 1], s = 100, c = 'green', label = 'Cluster 3')
plt.scatter(X[y_kmeans == 3, 0], X[y_kmeans == 3, 1], s = 100, c = 'cyan', label = 'Cluster 4')
plt.scatter(X[y_kmeans == 4, 0], X[y_kmeans == 4, 1], s = 100, c = 'magenta', label = 'Cluster 5')
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], s = 300, c = 'yellow', label = 'Centroids')
plt.title('Clusters of customers')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.legend()
plt.show()